stages:
    - test
    - build
unit-test:
    stage: test
    script: "C:\\'Program Files'\\Unity\\Hub\\Editor\\2019.2.12f1\\Editor\\Unity.exe \
    -projectPath . \
    -runTests \
    -logFile \
    -testPlatform playmode"
    tags:
    - Unity
    - Orbbec

unity-build:
    stage: build
    script: echo 'Building'
    tags:
    - Unity
    - Orbbec