using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System;
public class CardManager : MonoBehaviour
{
    //Card manager singleton
    public static CardManager instance;
    public Text scoreDisplay;
    public Canvas cardCanvas;
    public GameObject tutorialScreen;
    public GameObject correctImage, failImage;
    // the GameObject that represent the left and right hand of the player
    public GameObject leftHand, RightHand;
    private float feedbackDisplayTime = 2.0f;
    private float feedbackCounter = 0;
    private bool showWrongAnswerFeedback;
    private bool showRightAnswerFeedback;

    private int tutorialCount = 0;
    //Placeholder empty GameObjects in the scene
    [SerializeField]
    private GameObject[] placeholders;
    [SerializeField]
    private Card[] cardNames;

    //random Text is for display the name of the object the player is supposed to choose
    [SerializeField]
    private Text randomText;
    public List<string> currentCardName = new List<string>();
    // the int of the card chosen by player
    public int selectedCard;
    // the int of the correct card generated by the engine
    private int correctCard;
    // guessCount is the number of guesses the player has made
    private int guessCount = 0;
    // maxGuess is the maximum number of guesses the player can make, default value is 5
    // can be changed in the editor
    public int maxGuess = 5;

    // endGameCanvas is the canvas that is the canvas that contains resultText 
    public Canvas endGameCanvas;
    // resultText is used to display info to player when they finished a game
    public Text resultText;
    // player scores when they play the game, 50 points if they guess correctly, -20 if they guess incorrectly
    private int score = 0;

    
    void Awake()
    {
        correctImage.SetActive(false);
        failImage.SetActive(false);
        //Ensures that only one instance of CardManager exists
        if (instance != null)
        {
            //Destroy instance if CardManager exists
            Destroy(gameObject);
        }
        //Set current to CardManager
        instance = this;
        DontDestroyOnLoad(this);
        //AssignSprites();
    }
    private void Update()
    {   
        // display feedback to player after they have chosen the card
        if (showWrongAnswerFeedback)
        {

            if (feedbackCounter < feedbackDisplayTime)
            {
                failImage.SetActive(true);
                RightHand.SetActive(false);
                leftHand.SetActive(false);
            }
            else
            {
                failImage.SetActive(false);
                showWrongAnswerFeedback = false;
                feedbackCounter = 0;
                RightHand.SetActive(true);
                leftHand.SetActive(true);
            }
            feedbackCounter += Time.deltaTime;
        }

        if (showRightAnswerFeedback)
        {
            if (feedbackCounter < feedbackDisplayTime)
            {
                correctImage.SetActive(true);
                RightHand.SetActive(false);
                leftHand.SetActive(false);
            }
            else
            {
                correctImage.SetActive(false);
                showRightAnswerFeedback = false;
                feedbackCounter = 0;
                RightHand.SetActive(true);
                leftHand.SetActive(true);

            }
            feedbackCounter += Time.deltaTime;
        }
    }

    // reset the game state after the user has done playing with the game
    public void ResetGame()
    {
        guessCount = 0;
        scoreDisplay.text = "0";
        score = 0;
        endGameCanvas.gameObject.SetActive(false);
        AssignSprites();
    }

    public void CheckAnswer()
    {
        guessCount++;
        //check if answer is correct, if correct, add 50 to score, if incorrect minus 20 from score
        if (selectedCard == correctCard + 1)
        {
            Debug.Log("correct");
            FindObjectOfType<SoundManager>().Play("correctAnswer");
            score += 50;
            scoreDisplay.text = score.ToString();
            showRightAnswerFeedback = true;
        }
        else
        {
            Debug.Log("incorrect");
            FindObjectOfType<SoundManager>().Play("incorrectAnswer");
            score -= 20;
            scoreDisplay.text = score.ToString();
            showWrongAnswerFeedback = true;
        }

        //after checking for score, move to end round
        EndRound();
    }

    private void EndRound()
    {
        // end round is to display answer result and feedback to player
        if (guessCount < maxGuess  )
        {
            // start the next round
            AssignSprites();
        }
        else
        {
            EndGame();
        }
    }

    private void EndGame()
    {
        cardCanvas.gameObject.SetActive(false);
        endGameCanvas.gameObject.SetActive(true);

        if (score <= 0)
        {
            resultText.text = "Hyvä!" + System.Environment.NewLine + " Kiitos pelaamisesta";
        }
        else
        {
            resultText.text = "Hyvä! " + score.ToString() + " pistettä!";
        }
    }

    // start the game round by assigning the sprite to the 3 objects in the scene
    public void AssignSprites()
    {
        //Creates a list from Card array for later removal
        List<Card> activeCards = new List<Card>(cardNames);
        //clear list for old card name before assign new ones
        currentCardName.Clear();
        //Loads a sprite for each placeholder
        for (int i = 0; i < placeholders.Length; ++i)
        {
            //Chooses a random number below the Card count
            int rand = UnityEngine.Random.Range(0, activeCards.Count);
            //Instantiates a Card at position rand
            Card randCard = activeCards[rand];
            //Sets the sprite of placeholder GameObject to the sprite component of randCard
            placeholders[i].GetComponent<SpriteRenderer>().sprite = randCard.cardImage;
            //Removes the randCard to prevent duplicate sprites from being selected
            activeCards.Remove(randCard);
            //add name of randcard to card name list for display
            currentCardName.Add(randCard.cardType.ToString());
        }
        RandomText();
    }


    private void RandomText()
    {
        //Selects a random card name from the 3 cards shown
        int rand = UnityEngine.Random.Range(0, currentCardName.Count);
        randomText.text = currentCardName[rand];
        correctCard = rand;
    }
}
